### PR TITLE
docs: Add letsencrypt docker-compose example

### PR DESCRIPTION
**Pull request by b-zurg**
## Description:
This addition is meant to address the lack of exposure of how to use the linuxserver letsencrypt image with bookstack together even though they work amazingly well with each other.  

## Benefits of this PR and context:

I think many would want to have an https example with bookstack and might be turned away by the digging that's required to figure it out.  Setting up nginx and letsencrypt is not so much fun and it can all be automated away with docker-compose.

## How Has This Been Tested?

I have tried out this compose file and the instructions on a personal digital ocean vps.

### CODE REVIEW

**Comment by jessica-mulein** [comment]
+1 for concept.. Will report back once successfully installed as well and reaffirm ;)

**Comment by aptalca** [comment]
Thanks for the PR, but we don't publish compose yamls for letsencrypt integration. The compose snippets are also auto generated from a template (the whole readme is). Even if me merge this PR, all these changes would be overwritten with the old one generated from template by our ci during build.

We do provide preset proxy confs as part of letsencrypt, which are pulled in from here: https://github.com/linuxserver/reverse-proxy-confs/blob/master/bookstack.subdomain.conf.sample

Plus, adding an example letsencrypt config that requires quite a bit of user customization, without listing or describing any of these options would be very confusing to an end user. They are better off following the instructions for the letsencrypt image in its repo, where each option is described in detail.

**Comment by b-zurg** [comment]
Perhaps a mention could be put somewhere about the letsencrypt image? My main purpose was to just try to make an SSL setup for bookstack more obviously available. How do you think that is best accomplished?

**Comment by jessica-mulein** [comment]
Personally, I feel like needing a proxy out in front to serve SSL adds a failure point as well as redundant image, memory, and CPU overhead. A more integrated solution would be optimal. It feels really silly to need two separate docker containers running (plus mysql if not already commonly shared resource) and pass the data through all of the piping between them.

**Comment by aptalca** [comment]
@jessica-mulein adding letsencrypt/ssl support to every container we provide would create a lot of redundancies. SSL termination only needs one point source (on port 443), which would be the letsencrypt image. You can reverse proxy all other services through that one container.

**Comment by aptalca** [comment]
@b-zurg I see your point. I'll discuss with the team

**Pull request closed without merging**
