### PR TITLE
Added support for the BookStack System CLI

### LINKED ISSUE #170: [BUG] bookstack-system-cli backup can't be run
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When running `bookstack-system-cli backup` from command line while in `/app/www` an error occurs:
The "zip" PHP extension is required to run this command

grafik

### Expected Behavior

The command should be able to create a backup file.

### Steps To Reproduce

1. Log into Docker container
2. cd /app/www
3. ./bookstack-system-cli backup

### Environment

```markdown
- OS: Ubuntu 22.04
- How docker service was installed: Docker repo
```

### CPU architecture

x86-64

### Docker creation

```bash
version: "2"
services:
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 9005:8080
    environment:
      - ADMINER_DEFAULT_SERVER=mariadb
  bookstack_ldap:
    image: lscr.io/linuxserver/bookstack:latest
    container_name: bookstack_ldap
    environment:
      - [...]
    volumes:
      - bookstack:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    depends_on:
      - bookstack_db
      - drawio
  drawio:
    image: jgraph/drawio:latest
    restart: unless-stopped
    container_name: drawio
    ports:
      - 8080:8080
      - 8443:8443
  bookstack_db:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: MariaDB
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=[...]
      - TZ=Europe/Berlin
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=[...]
    volumes:
      - mariadb:/config
    ports:
      - 3306:3306
    restart: unless-stopped
volumes:
  mariadb:
   external: true
   name: mariadb
  bookstack:
   external: true
   name: bookstack
```

### Container logs

```bash
[migrations] started
[migrations] 01-nginx-site-confs-default: skipped
[migrations] 02-default-location: skipped
[migrations] done
───────────────────────────────────────
      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 
   Brought to you by linuxserver.io
───────────────────────────────────────
To support LSIO projects visit:
https://www.linuxserver.io/donate/
───────────────────────────────────────
GID/UID
───────────────────────────────────────
User UID:    1000
User GID:    1000
───────────────────────────────────────
using keys found in /config/keys
App Key found - setting variable for seds
Running config - DB_HOST set
Waiting for DB to be available
   INFO  Nothing to migrate.  
**** The following active confs have different version dates than the samples that are shipped. ****
**** This may be due to user customization or an update to the samples. ****
**** You should compare the following files to the samples in the same folder and update them. ****
**** Use the link at the top of the file to view the changelog. ****
┌────────────┬────────────┬────────────────────────────────────────────────────────────────────────┐
│  old date  │  new date  │ path                                                                   │
├────────────┼────────────┼────────────────────────────────────────────────────────────────────────┤
│ 2018-03-06 │ 2023-04-13 │ /config/nginx/site-confs/default.conf                                  │
│            │ 2023-04-13 │ /config/nginx/nginx.conf                                               │
│ 2022-08-05 │ 2022-08-20 │ /config/nginx/ssl.conf                                                 │
└────────────┴────────────┴────────────────────────────────────────────────────────────────────────┘
[custom-init] No custom files found, skipping...
[ls.io-init] done.
```

### PR DESCRIPTION
**Pull request by ssddanbrown**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

------------------------------

 - [x] I have read the [contributing](https://github.com/linuxserver/docker-bookstack/blob/master/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications

------------------------------

## Description:

This updates the image with the requirements need to run the now-included "BookStack System CLI". 
This is a new CLI that automates certain admin-level operations like backup/restore.

To achieve support, the image needed to be updated with php-zip extension support, and the `mariadb-client` client.
These changes , specifically the addition of `mariadb-client`, does lead to an increase in image size from approximately 280MB to 315MB. I do think this is worth it, especially as I can see some utility of having `mariadb-client` available for debug purposes outside just the context of the CLI, but that's not my call to make hence why I'm highlighting this size increase here.

Upon the above added packages, this also adds the newly added default BookStack backup directory to the folders that get linked to the `/config` volume, so that this backup folder is accessible via the mounted volume.

With these changes you'd able able to run the CLI like so:

```bash
# Create a backup
docker compose exec bookstack /app/www/bookstack-system-cli backup

# Restore an existing backup ZIP
docker compose exec bookstack /app/www/bookstack-system-cli restore /config/www/backups/bookstack-backup-2023-05-23-120213.zip
```

I did not update the readme yet with details of the CLI, since this CLI is in early alpha stages, so I don't want to actively advise it's usage right now, but it might be something to add in the future (Alongside details of calling the standard artisan command line).

## Benefits of this PR and context:

This allows usage of the newly added BookStack System CLI.
Closes #170 

While there are alternative or direct means to backup content in this container-based setup (Via direct volume files and/or via DB dumps), this CLI automates these actions in a standard manner, which could be especially useful for users looking to migrate between different BookStack hosting options.

## How Has This Been Tested?

I have built the image on Linux (Fedora 38 / AMD64) and on MacOS  (ARM), then performed a backup and restore using the CLI on both.

## Source / References:

- Relevant issue: https://github.com/linuxserver/docker-bookstack/issues/170
- CLI details on the BookStack blog: https://www.bookstackapp.com/blog/bookstack-release-v23-05/#new-system-cli-early-alpha
- CLI project: https://github.com/BookStackApp/system-cli

### CODE REVIEW

**Comment by nemchik** [comment]
This will need to be rebased now that https://github.com/linuxserver/docker-bookstack/pull/174 has merged.

Key points:

- php 8.2
- php zip extension is now included in the base image (not required in the Dockerfiles here)
- armhf is deprecated and removed

All that being said, I'm not a fan of adding 200mb+ to the image, and I think it might be better to recommend via the readme to use our universal package install mod https://github.com/linuxserver/docker-mods/tree/universal-package-install if you want this functionality.

**Comment by thespad** [comment]
Sounds like an idea mod candidate really.

**Comment by ssddanbrown** [comment]
> All that being said, I'm not a fan of adding 200mb+ to the image

Just to confirm, the image size change I observed was approximately from 280MB to 315MB, so a ~35MB change. Unless I've misunderstood and the 200mb referenced is via another form of measurement.

**Comment by nemchik** [comment]
> > All that being said, I'm not a fan of adding 200mb+ to the image
> 
> Just to confirm, the image size change I observed was approximately from 280MB to 315MB, so a ~35MB change. Unless I've misunderstood and the 200mb referenced is via another form of measurement.

I misread your initial post and thought you meant there was roughly a 200mb increase in the image size by including the additional package.

~35mb is definitely a lot less, but still a pretty decent number.

I don't have a strong opinion here, and I don't use bookstack at all, so I'll see if the rest of the team would like to chime in and if there are no other opinions I'll approve once the PR is rebased.

**Comment by thespad** [comment]
Quick build test, existing image is 287MB on disk, adding mariadb-client takes it to 361MB on disk so ~75MB. I don't think that's a problem for core functionality even if it's not going to be used by everyone.

**Comment by thespad** [comment]
@ssddanbrown I've rebased against the current master branch, let me know if you're happy and if so we'll get it merged.

**Comment by ssddanbrown** [comment]
Thanks @thespad.
Just gave this a test build and run on mac (arm64).

### PHP Timezone Issue

I noticed this error appearing whenever PHP is ran (Particularly via the CLI):

```
PHP Warning:  PHP Startup: Invalid date.timezone value '', using 'UTC' instead in Unknown on line 0
```

It looks like PHP `date.timezone` handling [changed in php8.2](https://github.com/php/php-src/pull/8594/files).
Within the base image, a `php-local.ini` is generated upon container start-up:

https://github.com/linuxserver/docker-baseimage-alpine-nginx/blob/71cc706de6cd077d4649a3a1a996a95e4601212a/root/etc/s6-overlay/s6-rc.d/init-php/run#L6

If the user is not passing a `TZ` env option, this generates `date.timezone` with an empty value.
I don't think the `TZ` option has ever been a default value for the example compose setup in the readme, and I don't think there's been a fallback default value.
I checked on a few of my past linuxserver compose setups, All of them have an empty `date.timezone`.
This hasn't been an issue before, but now in PHP8.2 it causes the above warning.
I think many setups upgrading to the latest image versions would have this warning appear (Also shows up in container start-up logs as PHP commands are ran).

### BookStack System CLI

The CLI exits upon unexpected PHP output, so the above scenario causes the CLI to stop upon certain actions.
Otherwise, running with a valid `date.timezone` (Via setting that option in `php-local.ini` or originally running with a `TZ` env option), allows backup and restore via the CLI to work as expected.

### Summary

I see the timezone issue to be tangential to this PR.
I'm happy to go ahead with this being merged, but users with an invalid/empty timezone may have trouble using this until that's addressed for their setup.
Probably could do with a separate follow-up PR to update the example docker-compose with a default valid `TZ` option, and/or a script to fix existing empty `date.timezone` (Could maybe wait to assess impact before going down that road).

**Comment by nemchik** [comment]
The timezone issue will be fixed by https://github.com/linuxserver/docker-baseimage-alpine-nginx/pull/143

**Review by thespad — APPROVED** [review]

**Pull request merged**
